### ISSUE TITLE
Smashing compile error

### ISSUE THREAD

**Issue by Smartie31** [etm/opcua-smart#11]
Hi,

I am trying to use this gem on my raspberry Pi 4 with smashing dashboard but when I run "smashing start"  I get the following error:

bundler: failed to load command: thin (/usr/local/bin/thin)
NameError: uninitialized constant OPCUA
  /home/pi/Documents/pi_dashboard/jobs/table.rb:5:in `<top (required)>'
  /var/lib/gems/2.5.0/gems/smashing-1.3.5/lib/dashing/app.rb:177:in `require'
  /var/lib/gems/2.5.0/gems/smashing-1.3.5/lib/dashing/app.rb:177:in `block in require_glob'
  /var/lib/gems/2.5.0/gems/smashing-1.3.5/lib/dashing/app.rb:176:in `each'
  /var/lib/gems/2.5.0/gems/smashing-1.3.5/lib/dashing/app.rb:176:in `require_glob'
  /var/lib/gems/2.5.0/gems/smashing-1.3.5/lib/dashing/app.rb:187:in `<top (required)>'
  /var/lib/gems/2.5.0/gems/smashing-1.3.5/lib/dashing.rb:3:in `require'
  /var/lib/gems/2.5.0/gems/smashing-1.3.5/lib/dashing.rb:3:in `<top (required)>'
  config.ru:1:in `require'
  config.ru:1:in `block in <main>'
  /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
  /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /var/lib/gems/2.5.0/gems/thin-1.8.1/lib/rack/adapter/loader.rb:33:in `eval'
  /var/lib/gems/2.5.0/gems/thin-1.8.1/lib/rack/adapter/loader.rb:33:in `load'
  /var/lib/gems/2.5.0/gems/thin-1.8.1/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
  /var/lib/gems/2.5.0/gems/thin-1.8.1/lib/thin/controllers/controller.rb:72:in `start'
  /var/lib/gems/2.5.0/gems/thin-1.8.1/lib/thin/runner.rb:203:in `run_command'
  /var/lib/gems/2.5.0/gems/thin-1.8.1/lib/thin/runner.rb:159:in `run!'
  /var/lib/gems/2.5.0/gems/thin-1.8.1/bin/thin:6:in `<top (required)>'
  /usr/local/bin/thin:23:in `load'
  /usr/local/bin/thin:23:in `<top (required)>'

My .rb file looks like the following:

#require_relative '../lib/opcua/client'
#require opcua/client

client = OPCUA::Client.new("opc.tcp://192.168.1.50:4840")
client.subscription_interval = 100

if (node = client.get 2, 'Pressure')
  p node
  p node.value
else
  p 'invalid nodeid'
end

When I run "ldconfig -p | grep libopen6" I get this:
	libopen62541.so.1 (libc6,hard-float) => /usr/local/lib/libopen62541.so.1
	libopen62541.so (libc6,hard-float) => /usr/local/lib/libopen62541.so

Hoppefully you can help me.

Thanks in advance!!

**Comment by Smartie31** [comment]
I needed to include the opcua gem in the gemfile of the Smashing dashboard
